backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "home"
    label: "Homepage Content"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "content/home.json"
        fields:
          - { label: "Book Now Link", name: "book_link", widget: "string" }
          - { label: "Headline", name: "headline", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "DJ Name", name: "dj_name", widget: "string" }
          - { label: "DJ Info", name: "dj_info", widget: "text" }
